apiVersion: v1
kind: Pod
metadata:
  name: sailorpod
spec:
  containers:
    - name: sailor
      image: raghravi94/sailor:1.0
      ports:
        - name: tomcatport
          containerPort: 80
          protocol: TCP